blog/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from blogapp  import urls as blog_url
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(blog_url)),
]

# urlpatterns += staticfiles_urlpatterns()

blogapp/urls.py
from django.urls import path
from .views import blog_home, blog_detail,signup_page,login_page,log_out,like_post

app_name = 'blogapp'


urlpatterns = [
    path('', blog_home,name='blog_home'),
    path('logout', log_out,name='log_out'),
    path('login',login_page, name='login'),
    path('signup',signup_page,name='signup'),
    path('like_post',like_post, name='like_post'),
    path('details-/<slug:post_slug>/',blog_detail , name="second"),


]

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.contrib.auth.models import AbstractUser  , BaseUserManager
# from django.utils.translation import  ugettext_lazy as _
# from django.dispatch import receiver
# from django.db.models.signals import post_save


class Blog(models.Model):
    title = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32,unique=True)
    body = models.TextField()
    date = models.DateTimeField(auto_now=True)
    like = models.ManyToManyField(User, blank=True, related_name='post_like')
    updated=models.DateTimeField(auto_now=True , auto_now_add=False)
    timestamp=models.DateTimeField(auto_now=False , auto_now_add=True)
    def __str__(self):
        return self.title

    def half(self):
        return self.body[:50] + "...."

    @property
    def get_absolute_url(self):
        return "/details-/%s/" %(self.slug)

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comment')
    comment = models.CharField(max_length=512)
    created = models.DateTimeField(auto_now=True)
    email = models.EmailField()

    def __str__(self):
        return self.blog.title

    class Meta:
        ordering = ('-created',)


class Profile(models.Model):
    CATEGORY_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('T','Transgender')
    )


    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='profiles', related_query_name='profile')
    phone = models.IntegerField(default=0)
    birthday=models.DateField(auto_now=False, null=True, blank=True)
    gender = models.CharField(max_length=200, choices=CATEGORY_CHOICES)
    city=models.CharField(max_length=50,default="", null=True )

    def __str__(self):
        return self.user.username


# class UserManager(BaseUserManager):
#     use_in_migrations=True
# def save(self, *args, *kwargs):
#     u = super(User, self).save(*args, **kwargs)
#     Profile.objects.get_or_create(user=u.id)
#     return u

#
# @receiver(post_save , sender=User)
# def create_user_profile(sender , instance ,  created , **kwargs):
#     print("under create")
#     if created and not instance.is_staff:
#         # attrs_needed = ['_otherfield',]
#         print(kwargs)
#
#         # if all(hasattr(instance, attr) for attr in attrs_needed):
#         print("hello2")
#         Profile.objects.create(user=instance)  #, phone=instance._otherfield
#         print("hello3")
#         instance.profile.save()
#         print("hello1")


# @receiver(post_save , sender=User, weak=False)
# def my_handler(sender , instance ,  created , **kwargs):
#     print("hello1dfsfs")
#
#     if created and not instance.is_staff:
#         attrs_needed = ['_otherfield', ]
#         if all(hasattr(instance, attr) for attr in attrs_needed):
#             Profile.objects.get_or_create(user=instance, phone=instance._otherfield)
#             instance.profiles.save()
#             print("hello1")

blogapp/forms.py
from django import forms
from django.contrib.auth.models import User
from blogapp.models import Profile
from django.core.validators import validate_email

class CommentForm(forms.Form):
    comment=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Comment '}),required=True)
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter email '}), required=True)

class UserForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter UserName'}),
                               required=True, max_length=30)

    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter Email'}),
                            required=True, max_length=30)

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter First Name'}), required=True,
        max_length=30)

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Last Name'}), required=True,
        max_length=30)

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter Password'}), required=True,
        max_length=30)

    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter Password'}), required=True,
        max_length=30)

    class Meta():
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password', 'confirm_password']

    def clean_username(self):
        username=self.cleaned_data['username']
        if username.isdigit():
            raise forms.ValidationError("user must contain atleast a character")

        return username

    def clean_email(self):
        email=self.cleaned_data['email']
        try:
            verify=validate_email(email)
        except:
             raise forms.ValidationError("Email is not Valid")
        return email

    def clean_confirm_password(self):

        password=self.cleaned_data.get('password')


        confirm_password=self.cleaned_data.get('confirm_password')


        if(password!=confirm_password):

            raise  forms.ValidationError("confirm password is not matched ")
        else:
            if(len(password)<8):
                raise forms.ValidationError("password must be atleast  8 character")
            if(password.isdigit()):
                raise forms.ValidationError("password must contain atleast a character")
            if(password.isalnum()):
                raise forms.ValidationError("Password must contain atleast a special character")
        return password

YEARS= [x for x in range(1940,2021)]
class ProfileForm(forms.ModelForm):
    phone=forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter mobile number '}), required=True)
    city= forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter city'}), required=True,
        max_length=30)

    birthday= forms.DateField(label='Birthday', widget=forms.SelectDateWidget(years=YEARS))
    class Meta:
        model = Profile
        fields=['phone','city','gender','birthday']

    def clean_phone(self):
        phone=self.cleaned_data.get('phone')
        length=len(str(phone))
        if (length>10 or length<10):
            raise forms.ValidationError("mobile number must be of 10 digit")
        return phone

blogapp/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.contrib.auth import logout
from blogapp.forms import CommentForm, UserForm, ProfileForm
from .models import Blog, Comment, Profile
from django.contrib.auth import authenticate ,login
from django.http import JsonResponse, HttpResponseRedirect


def signup_page(request):
    if request.method == "POST":
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)

        if (user_form.is_valid() and profile_form.is_valid() ):

            username=user_form.cleaned_data['username']
            email=user_form.cleaned_data['email']
            first_name=user_form.cleaned_data['first_name']
            last_name=user_form.cleaned_data['last_name']
            password=user_form.cleaned_data['password']
            phone = profile_form.cleaned_data['phone']

            user= User.objects.create(username=username, last_name=last_name, first_name=first_name, email=email)
            user.set_password(password)
            user._otherfield = phone
            user.save()
            # print(user)
            # User.objects.create(**user_form.cleaned_data)

            phone = profile_form.cleaned_data.get('phone')
            birthday= profile_form.cleaned_data.get('birthday')
            gender = profile_form.cleaned_data.get('gender')
            city = profile_form.cleaned_data.get('city')
            Profile.objects.create(user=user, phone=phone,city=city, gender=gender, birthday=birthday)
            return redirect("/")
        else:

            return render(request,"signup.html",{"user_form":user_form,"phone_form":profile_form})
    else:
        user_form = UserForm()
        profile_form = ProfileForm()
        return render(request,"signup.html",{"user_form":user_form,"phone_form":profile_form})


def blog_home(request):
    blogs = Blog.objects.all().order_by('date')

    name = ""
    if request.user.is_authenticated:
        name = request.user.first_name


    return render(request, 'first.html', {'blg': blogs,'name':name})


def blog_detail(request, post_slug):
    blog = Blog.objects.get(slug=post_slug)

    is_liked = False
    if blog.like.filter(id=request.user.id).exists():
        is_liked=True
    name = ""
    if request.user.is_authenticated:
        name = request.user.first_name


    blog_comments = Comment.objects.filter(blog__id=blog.id)

    if request.method == "POST":
        comment_show = CommentForm(request.POST)
        if request.user.is_authenticated:
            if comment_show.is_valid():
                Comment.objects.create(blog=blog, comment=comment_show.cleaned_data['comment'],
                                       email=comment_show.cleaned_data['email'])
                return redirect("/details-/" + post_slug)
            else:

                for field in comment_show.errors :
                    comment_shows=field
                name = request.user.first_name

                return render(request, "second.html",
                              {'blg1': blog, 'blog_comments': blog_comments, "comment_forms": comment_show,
                               'errors': comment_shows,'name':name, 'is_liked':is_liked})
        else:
            return redirect("blogapp:login")
            print("tongo")


    comment_forms = CommentForm()
    return render(request, 'second.html',
                  {'blg1': blog, 'blog_comments': blog_comments, "comment_forms": comment_forms, 'name': name, 'is_liked':is_liked})


def login_page(request):
    if  request.method == "POST":


        username=request.POST.get('username')
        password=request.POST.get('password')
        if (username.isdigit()):
            user=Profile.objects.get(phone=username).user


            if user.check_password(password):
                return redirect("/")
            else:
                return HttpResponse("<h1> INVALID </h1>")
        else:


            user = authenticate(username=username, password=password)

            if user is not None:
                login(request,user)
                return redirect("/")
            else:
                return HttpResponse("<h1> INVALID </h1>")
    else:

        return render(request, "login.html")



def log_out(request):

    logout(request)
    return redirect("/")


def like_post(request):
    if request.user.is_authenticated:

        post=get_object_or_404(Blog, id=request.POST.get('post_id'))


        is_liked = False
        if post.like.filter(id=request.user.id).exists():
            post.like.remove(request.user)
            is_liked=False
        else:
            post.like.add(request.user)
            is_liked=True


        return HttpResponseRedirect(post.get_absolute_url)
    else:
        return redirect("blogapp:login")

blogapp/templates/base_layout.html
{% load static %}
{% load blog_tag %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BLOGGING</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/2.9.33/bluebird.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">





    <style>
body {
  margin: 0;
  font-family: Helvetica, sans-serif;
  background-color: #f4f4f4;
}

a {
  color: #000;
}

/* header */

.header {
  background-color: #fff;
  box-shadow: 1px 1px 4px 0 rgba(0,0,0,.1);
  position: fixed;
  width: 100%;
  z-index: 3;
}

.header ul {
  margin: 0;
  padding: 0;
  list-style: none;
  overflow: hidden;
  background-color: #fff;
}

.header li a {
  display: block;
  padding: 20px 20px;
  border-right: 1px solid #f4f4f4;
  text-decoration: none;
}

.header li a:hover,
.header .menu-btn:hover {
  background-color: #f4f4f4;
}

.header .logo {
  display: block;
  float: left;
  font-size: 2em;
  padding: 10px 20px;
  text-decoration: none;
}

/* menu */

.header .menu {
  clear: both;
  max-height: 0;
  transition: max-height .2s ease-out;
}

/* menu icon */

.header .menu-icon {
  cursor: pointer;
  display: inline-block;
  float: right;
  padding: 28px 20px;
  position: relative;
  user-select: none;
}

.header .menu-icon .navicon {
  background: #333;
  display: block;
  height: 2px;
  position: relative;
  transition: background .2s ease-out;
  width: 18px;
}

.header .menu-icon .navicon:before,
.header .menu-icon .navicon:after {
  background: #333;
  content: '';
  display: block;
  height: 100%;
  position: absolute;
  transition: all .2s ease-out;
  width: 100%;
}

.header .menu-icon .navicon:before {
  top: 5px;
}

.header .menu-icon .navicon:after {
  top: -5px;
}

/* menu btn */

.header .menu-btn {
  display: none;
}

.header .menu-btn:checked ~ .menu {
  max-height: 240px;
}

.header .menu-btn:checked ~ .menu-icon .navicon {
  background: transparent;
}

.header .menu-btn:checked ~ .menu-icon .navicon:before {
  transform: rotate(-45deg);
}

.header .menu-btn:checked ~ .menu-icon .navicon:after {
  transform: rotate(45deg);
}

.header .menu-btn:checked ~ .menu-icon:not(.steps) .navicon:before,
.header .menu-btn:checked ~ .menu-icon:not(.steps) .navicon:after {
  top: 0;
}

/* 48em = 768px */

@media (min-width: 48em) {
  .header li {
    float: left;
  }
  .header li a {
    padding: 20px 30px;
  }
  .header .menu {
    clear: none;
    float: right;
    max-height: none;
  }
  .header .menu-icon {
    display: none;
  }
}

    </style>
<style>

.like-btn {
  background: navy;
  border: none;
  padding: 0.5rem 0.5rem;
  color: #fff;
  font-size: 18px;
  text-align: left;
  min-width: 11rem;
  box-sizing: border-box;
  text-align: center;
  line-height: 2;
}

.like-btn__spinner {
  vertical-align: middle;
}


.button:hover {background-color: #3e8e41}

</style>
</head>

<body background="{% static 'background.jpg'%}">

<nav class="nav navbar">
    <div class="navbar-header">
<header class="header">
<div class="col-md-4 ">
  <a href="/" class="logo"><img src="{% static 'logo11.png' %}" width="60" height="60" alt="">BLOGGING </a>

</div>
    <div class="col-md-4">

      <ul>
          <li><a><h3>WELCOME {{name|capfirst}}</h3></a></li>
      </ul>

</div>
    <div class="col-md-4">
  <input class="menu-btn" type="checkbox" id="menu-btn" />
  <label class="menu-icon" for="menu-btn"><span class="navicon"></span></label>
  <ul class="menu">
    {% if user.is_authenticated %}
      <li class="active">
                <a href="/logout">LOGOUT</a>
            </li>
    {% else %}
      <li class="active">
                <a href="/login">LOGIN / SIGNUP </a>
            </li>
    {% endif %}


  </ul>
</div>
</header>
    </div>
</nav>

{% block content %}

{% endblock %}

</body>
</html>

blogapp/templates/first.html
{% extends 'base_layout.html' %}
{% load static %}
{% load blog_tag%}

{% block content %}


<center>
<div id="content">
<div class="container">
    <div class="row">
    <div class="col-md-6 column" style="background-color: #e3f2fd;">
        <div id="content">
        {% for x in blg %}
        <h2 style="background-color: #e3f2fd;"> <a href="{{ x.get_absolute_url }}">{{x.title }} </a></h2>

            <p>{{x.half}}</p>

            <p>{{x.date}}</p>
        {% endfor %}
        </div>
    </div>

            <div class="col-md-6 column" style="background-color: #e3f2fd;">
                <div id="sidebar">
            <h3>Most commented Post</h3>
            {% get_most_commented_posts %}
            </div>
        </div>
    </div>
</div>


</div>
      <img src="{% static 'thanking.png' %}">
   </center>



{% endblock %}

    <!--/second/{{ x.slug}}-->

<!--    {% url 'blogapp:second' x.slug%}-->

blogapp/templates/login.html
{% extends 'base_layout_login.html' %}
{% load static %}
{% block content %}
<center>
<header><h1 style="color:black">BLOGGING</h1></header>
    <section >

        <div class="container-fluid">
            <div class="row full-height-vh">
                <div class="custom_width">
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <div class="card card-inverse gradient-indigo-purple text-center width-400">
                        <div class="card-img overlap">
                            <div class="login_av"><img alt="element 06" class="mb-1" src="{% static 'logo11.png' %}"
                                                       width="190"></div>
                            <!-- <img alt="element 06" class="mb-1" src="assets/img/logo.png" width="190"> -->
                        </div>
                        <div class="card-body">
                            <div class="card-block">
                                <h2>Login</h2>
                                <form method="POST" action="/login">
                                    {%csrf_token%}
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <input type="text" class="form-control black" name="username" id="username"
                                                   placeholder="Username" required>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <input type="password" class="form-control black" name="password"
                                                   id="inputPass" placeholder="Password" required>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <label class="custom-control custom-checkbox mb-2 mr-sm-2 mb-sm-0">
                                                    <input type="checkbox" class="custom-control-input" checked>
                                                    <span class="custom-control-indicator ml-4"></span>
                                                    <span class="pl-2">Remember Me</span>
                                                </label>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-12" >
                                              <a><button type="submit" class="btn btn-pink btn-block btn-raised" >SUBMIT</button></a>
                                            <!-- <button type="button" class="btn btn-secondary btn-block btn-raised">Cancel</button> -->
                                        </div>
                                    </div>
                                    </form>

                            </div>
                        </div>


                        <div class="form-group" >
                            <div class="col-md-12" >
                            <div class="float-left"><a>OR</a></div>
                                            <!-- <div class="float-right"><a (click)="onRegister()">New User?</a></div> -->
                         </div>
                   </div>

                        <div class="card-footer">
                            <div class="col-md-12" >
                           <a href="/signup"><button type="submit" class="btn btn-pink btn-block btn-raised" >SIGN_UP</button></a>
                        </div>
                        </div>
            </div>
                </div>
            </div>
        </div>

    </section>

</center>

{% endblock %}

blogapp/templates/most_commented_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Latest_posts</title>
</head>
<body>

<ul>

    {% for post in most_commented %}

        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>

        </li>
    {% endfor %}
</ul>
</body>
</html>

blogapp/templates/second.html
{% extends 'base_layout.html' %}

{% load static %}


{% block content %}




<script>
var error1;
error1 ="{{errors }}";
if(error1){
alert("Please enter valid email address ");
}
</script>
<div class="col-md-6" >
    <center>
        <div class="blg1" style="background-color:#FFFFFF; font-family:verdana;">

        <h2 style="font-family:verdana;color:#000080" ;> {{blg1.title }} </h2>
        <b style="color:#338AFF">{{blg1.date}}</b><br>
        <I>{{blg1.body}}</I>


        <form action="/like_post" method="POST">
            <p>Likes: {{blg1.like.count }}</p>
                 {%csrf_token%}

         {% if is_liked %}
            <p>
             <button type="submit"  name="post_id" value="{{ blg1.id}}" class="js-like-button like-btn glyphicon glyphicon-thumbs-down "> Dislike</button></p>
         {% else %}

             <button type="submit"  name="post_id" value="{{ blg1.id}}" class="js-like-button like-btn glyphicon glyphicon-thumbs-up"> Like</button></p>
         {% endif %}
        </form>



        </div>

    </center>
</div>
<div class="col-md-3">

        <form action="{% url 'blogapp:second' blg1.slug%}  " method="POST">
            {%csrf_token%}
            {{comment_forms.as_p}}
            <button class="btn btn-primary" type="submit">Submit comment</button>
        </form>
</div>


   <div class="col-md-3">
        <h1 style="background-color:#FFFFFF;font-family:verdana;color:#000080" ;" >COMMENTS</h1>

        <div class="comment" style="font-size:120%;">

            {% for comment in blog_comments %}
            <br> <br>
            <h3>{{ comment.comment }}</h3>

            <h4>{{ comment.email }}</h4>

            {{ comment.created }}
            {% endfor %}

        </div>
   </div>
    <img src="{% static 'thanking.png' %}">


{% endblock %}

blogapp/templates/signup.html
{% extends 'base_layout_login.html' %}

{% load static %}
{% block content %}
<center><header><h1><img src="{% static 'logo11.png' %}">BLOGGING</h1></header></center>
<article >

  <form action="signup" method="POST">
    <div class="login-form" >
      <center>
    {%csrf_token%}
    {{user_form.as_p}}
    {{phone_form.as_p}}
</center>
    <button class="btn btn-primary"  type="submit">SUBMIT</button>
    </div>
</form>


</article>

{% endblock %}